### ISSUE TITLE
links in README are broken

### ISSUE THREAD

**Issue by tvt173** [Vlsir/Vlsir#19]
for example, for the raw layout protocol. link is broken. should be https://github.com/Vlsir/schema-proto/blob/main/layout/raw.proto. looks like it was moved under a `layout` subfolder since the time the README was last updated

**Comment by growly** [comment]
fixed, thanks.

we're going to rename `raw.proto` at some point soon (hopefully) if you want to weigh in on that: https://github.com/Vlsir/schema-proto/issues/3
