### ISSUE TITLE
Some means of automated testing `vlsirtools.spice`

### ISSUE THREAD

**Issue by dan-fritchman** [Vlsir/Vlsir#41]
We brick these simulator-drives more often than seemingly anything else, and for good reason: we don't really test them. 

Outlook for doing so: 

* Anything with a closed-source license basically won't happen, unless it's stood up separately on privately owned hardware
* Xyce installation is: 
  * Very easy on MacOS, CentOS/ RedHat Linux
  * Probably works on Windows? Idunno anything about Windows.
  * Very, very painful on Ubuntu/ Debian Linux. Like a full-day project. 
  * Relevant: our CI provider (GitHub Actions) supports Ubuntu, but not CentOS/ RedHat. 
* NgSpice is quite installable on all of the above, but is also in many respects "the worst" of these, both in and of itself, and in our support for it. 

Writing this makes me realize: we probably need something like the OS-testing matrix, or at least to swap out Ubuntu for testing Xyce.

**Comment by dan-fritchman** [comment]
Related: unit testing for each simulator essentially runs "if the simulator's available". Tests generally look like so: 

```python
@pytest.mark.skipif(
    not vlsirtools.xyce.available(),
    reason="No Xyce installation on path",
)
def test_xyce1():
    # ... do stuff ....
```

We would seem to want a test-option that says "such-and-such simulator **better be** available, or fail". This could be in the form of custom pytest command-line options, such as those deployed [here](https://github.com/Vlsir/Usb2Phy/blob/main/Usb2PhyAna/conftest.py).

**Comment by ThomasPluck** [comment]
Question: are we going to close this one when we have testing across Windows, MacOS and a Linux?

**Comment by dan-fritchman** [comment]
I think we should close this now, and should have once you added the simulation-focused test container!
