### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by joamatab** [Vlsir/Vlsir#58]
How can we add docs?

we would love to integrate gdsfactory with VLSIR for spice simulations

**Comment by dan-fritchman** [comment]
Great to hear!  
And also an easy answer: write some!  

I would also note that [hdl21.sim](https://github.com/dan-fritchman/Hdl21#spice-class-simulation), which makes these aways nicer to use, has quite a bit more.

**Comment by dan-fritchman** [comment]
Resolution: use hdl21.sim and enjoy!
